name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Check format
        run: dart format --set-exit-if-changed .

      - name: Run unit tests
        run: flutter test --coverage --test-randomize-ordering-seed random

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash | bash
